source ~/.sh/init.sh

load_modules ~/.sh/misc.sh ~/.sh/aliases.sh
load_modules_silent ~/.sh/host/misc.sh ~/.sh/host/aliases.sh

load_modules ~/.zsh/settings.zsh ~/.zsh/plugins.zsh
load_modules_silent ~/.zsh/host/settings.zsh ~/.zsh/host/plugins.zsh
